### ISSUE TITLE
Switch to typescript

### ISSUE THREAD

**Issue by mustafa-tariqk** [BasicallyOk/Knights-Tour-DCP#1]
Trust me your life will get better

**Comment by BasicallyOk** [comment]
Fuck Javascript but idk if typescript gonna work on DCP lol

**Comment by mustafa-tariqk** [comment]
its just a superset of js and iirc it compiles down to js anyways, worth a try so KDS can say it supports another lang

**Comment by jimmywarting** [comment]
I think typescript is a nightmare with it's darn build process, typescript don't run in browsers and never will.
[You might not need TypeScript... (syntax)](https://jimmywarting.github.io/you-might-not-need-typescript/)
